sonar.projectKey=Mustafa-Hussain-source_P06_Anomalous-Login-Detection-ELK
sonar.organization=mustafa-hussain-source
sonar.projectName=P06 Anomalous Login Detection ELK
sonar.sourceEncoding=UTF-8

# Source code
sonar.sources=Development/Sprint-3/app

# Tests
sonar.tests=Testing,Development/Sprint-4
sonar.test.inclusions=**/test_*.py

# Coverage
sonar.python.coverage.reportPaths=./coverage.xml

# Python version
sonar.python.version=3.12

# Exclusions
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/*.ipynb,**/node_modules/**,**/elk-weekly-report/**,**/elk-wazuh-compose/**
sonar.coverage.exclusions=Testing/**

sonar.verbose=true