# sonar.projectKey=Mustafa-Hussain-source_P06_Anomalous-Login-Detection-ELK
# sonar.organization=mustafa-hussain-source
# sonar.projectName=P06 Anomalous Login Detection ELK
# sonar.sourceEncoding=UTF-8

# # Restrict analysis to implemented Python backend and Sprint-4 automation code.
# # sonar.sources=Development/Sprint-3/app,Development/Sprint-4
# # sonar.tests=Development/Sprint-4
# sonar.sources=Development/Sprint-3/app
# sonar.tests=Testing,Development/Sprint-4
# sonar.python.coverage.reportPaths=coverage.xml
# sonar.test.inclusions=Development/Sprint-4/test_*.py
# sonar.python.version=3.12

# # Exclude generated, binary, and infrastructure-heavy folders from source analysis.
# sonar.exclusions=**/__pycache__/**,**/*.pyc,**/*.ipynb,**/node_modules/**,**/elk-weekly-report/**,**/elk-wazuh-compose/**,**/wazuh/**
# sonar.tests=Testing

sonar.projectKey=Mustafa-Hussain-source_P06_Anomalous-Login-Detection-ELK
sonar.organization=mustafa-hussain-source
sonar.projectName=P06 Anomalous Login Detection ELK
sonar.sourceEncoding=UTF-8

# Source code
sonar.sources=Development/Sprint-3/app

# Tests
sonar.tests=Testing,Development/Sprint-4

# Include all test files
sonar.test.inclusions=**/test_*.py

# Coverage
sonar.python.coverage.reportPaths=coverage.xml

# Python version
sonar.python.version=3.12

# Exclusions
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/*.ipynb,**/node_modules/**,**/elk-weekly-report/**,**/elk-wazuh-compose/**