input {
  file {
    path => "/Users/mohamamdmustafa/Documents/test_logs/*.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  grok {
    match => { "message" => "%{COMMONAPACHELOG}" }
  }
}

output {
  elasticsearch {
    hosts => ["https://localhost:9200"]
    index => "test-logs"
    ssl_enabled => true
    ssl_verification_mode => "none"
    user => "elastic"
    password => "bGzPTKvCQ+wnZj*0hvrt"
  }

  stdout {
    codec => rubydebug
  }
}