apiVersion: v1
kind: Service
metadata:
  name: alds-api
  namespace: alds
spec:
  type: NodePort
  selector:
    app: alds-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
